require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PayrollEmployeesController do

  # This should return the minimal set of attributes required to create a valid
  # PayrollEmployee. As you add validations to PayrollEmployee, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PayrollEmployeesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all payroll_employees as @payroll_employees" do
      payroll_employee = PayrollEmployee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:payroll_employees).should eq([payroll_employee])
    end
  end

  describe "GET show" do
    it "assigns the requested payroll_employee as @payroll_employee" do
      payroll_employee = PayrollEmployee.create! valid_attributes
      get :show, {:id => payroll_employee.to_param}, valid_session
      assigns(:payroll_employee).should eq(payroll_employee)
    end
  end

  describe "GET new" do
    it "assigns a new payroll_employee as @payroll_employee" do
      get :new, {}, valid_session
      assigns(:payroll_employee).should be_a_new(PayrollEmployee)
    end
  end

  describe "GET edit" do
    it "assigns the requested payroll_employee as @payroll_employee" do
      payroll_employee = PayrollEmployee.create! valid_attributes
      get :edit, {:id => payroll_employee.to_param}, valid_session
      assigns(:payroll_employee).should eq(payroll_employee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PayrollEmployee" do
        expect {
          post :create, {:payroll_employee => valid_attributes}, valid_session
        }.to change(PayrollEmployee, :count).by(1)
      end

      it "assigns a newly created payroll_employee as @payroll_employee" do
        post :create, {:payroll_employee => valid_attributes}, valid_session
        assigns(:payroll_employee).should be_a(PayrollEmployee)
        assigns(:payroll_employee).should be_persisted
      end

      it "redirects to the created payroll_employee" do
        post :create, {:payroll_employee => valid_attributes}, valid_session
        response.should redirect_to(PayrollEmployee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payroll_employee as @payroll_employee" do
        # Trigger the behavior that occurs when invalid params are submitted
        PayrollEmployee.any_instance.stub(:save).and_return(false)
        post :create, {:payroll_employee => {}}, valid_session
        assigns(:payroll_employee).should be_a_new(PayrollEmployee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PayrollEmployee.any_instance.stub(:save).and_return(false)
        post :create, {:payroll_employee => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payroll_employee" do
        payroll_employee = PayrollEmployee.create! valid_attributes
        # Assuming there are no other payroll_employees in the database, this
        # specifies that the PayrollEmployee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PayrollEmployee.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => payroll_employee.to_param, :payroll_employee => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested payroll_employee as @payroll_employee" do
        payroll_employee = PayrollEmployee.create! valid_attributes
        put :update, {:id => payroll_employee.to_param, :payroll_employee => valid_attributes}, valid_session
        assigns(:payroll_employee).should eq(payroll_employee)
      end

      it "redirects to the payroll_employee" do
        payroll_employee = PayrollEmployee.create! valid_attributes
        put :update, {:id => payroll_employee.to_param, :payroll_employee => valid_attributes}, valid_session
        response.should redirect_to(payroll_employee)
      end
    end

    describe "with invalid params" do
      it "assigns the payroll_employee as @payroll_employee" do
        payroll_employee = PayrollEmployee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PayrollEmployee.any_instance.stub(:save).and_return(false)
        put :update, {:id => payroll_employee.to_param, :payroll_employee => {}}, valid_session
        assigns(:payroll_employee).should eq(payroll_employee)
      end

      it "re-renders the 'edit' template" do
        payroll_employee = PayrollEmployee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PayrollEmployee.any_instance.stub(:save).and_return(false)
        put :update, {:id => payroll_employee.to_param, :payroll_employee => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payroll_employee" do
      payroll_employee = PayrollEmployee.create! valid_attributes
      expect {
        delete :destroy, {:id => payroll_employee.to_param}, valid_session
      }.to change(PayrollEmployee, :count).by(-1)
    end

    it "redirects to the payroll_employees list" do
      payroll_employee = PayrollEmployee.create! valid_attributes
      delete :destroy, {:id => payroll_employee.to_param}, valid_session
      response.should redirect_to(payroll_employees_url)
    end
  end

end
